[env]

[tools]
node = '24.11.1'
pnpm = 'latest'

[tasks.install]
description = "Install project dependencies"
run = 'pnpm install'

[tasks.build]
description = "Build the project"
run = 'pnpm build'

[tasks.biome-start]
description = "Starts the Biome daemon server process"
run  = 'pnpm biome start'

[tasks.biome-stop]
description = "Stops the Biome daemon server process"
run = 'pnpm biome stop'

[tasks.lint]
description = "Run the linter on a set of files"
run = 'pnpm biome check'

[tasks.fmt]
description = "Run the formatter on a set of files"
run = 'pnpm biome format'
